name: Run Web Scraper

on:
  schedule:
    # Run every day at 2 AM (UTC)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure scraper dependencies are listed
    
    - name: Run Scraper
      run: python principal_scraper.py  # Run your scraping script
    
    - name: Commit Results (Optional)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add scraped_data.json
        git commit -m "Update scraped data [$(date)]" || echo "No changes to commit"
        git push
