name: Run Principal Spider

on:
  schedule:
    # Run every minute
    - cron: '*/1 * * * *'
  workflow_dispatch:  # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cec_scraper/requirements.txt
    
    - name: Run Principal Spider
      run: |
        cd cec_scraper
        scrapy crawl principal  # Runs the spider
    
    - name: Commit Results (Optional)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add cec_scraper/output/*
        git commit -m "Update scraped data [$(date)]" || echo "No changes to commit"
        git push
